// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package entityprovidermock

import (
	"encoding/json"

	"github.com/asgardeo/thunder/internal/entityprovider"
	mock "github.com/stretchr/testify/mock"
)

// NewEntityProviderInterfaceMock creates a new instance of EntityProviderInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEntityProviderInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *EntityProviderInterfaceMock {
	mock := &EntityProviderInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EntityProviderInterfaceMock is an autogenerated mock type for the EntityProviderInterface type
type EntityProviderInterfaceMock struct {
	mock.Mock
}

type EntityProviderInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *EntityProviderInterfaceMock) EXPECT() *EntityProviderInterfaceMock_Expecter {
	return &EntityProviderInterfaceMock_Expecter{mock: &_m.Mock}
}

// CreateEntity provides a mock function for the type EntityProviderInterfaceMock
func (_mock *EntityProviderInterfaceMock) CreateEntity(entity *entityprovider.Entity, systemCredentials json.RawMessage) (*entityprovider.Entity, *entityprovider.EntityProviderError) {
	ret := _mock.Called(entity, systemCredentials)

	if len(ret) == 0 {
		panic("no return value specified for CreateEntity")
	}

	var r0 *entityprovider.Entity
	var r1 *entityprovider.EntityProviderError
	if returnFunc, ok := ret.Get(0).(func(*entityprovider.Entity, json.RawMessage) (*entityprovider.Entity, *entityprovider.EntityProviderError)); ok {
		return returnFunc(entity, systemCredentials)
	}
	if returnFunc, ok := ret.Get(0).(func(*entityprovider.Entity, json.RawMessage) *entityprovider.Entity); ok {
		r0 = returnFunc(entity, systemCredentials)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entityprovider.Entity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*entityprovider.Entity, json.RawMessage) *entityprovider.EntityProviderError); ok {
		r1 = returnFunc(entity, systemCredentials)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entityprovider.EntityProviderError)
		}
	}
	return r0, r1
}

// EntityProviderInterfaceMock_CreateEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEntity'
type EntityProviderInterfaceMock_CreateEntity_Call struct {
	*mock.Call
}

// CreateEntity is a helper method to define mock.On call
//   - entity *entityprovider.Entity
//   - systemCredentials json.RawMessage
func (_e *EntityProviderInterfaceMock_Expecter) CreateEntity(entity interface{}, systemCredentials interface{}) *EntityProviderInterfaceMock_CreateEntity_Call {
	return &EntityProviderInterfaceMock_CreateEntity_Call{Call: _e.mock.On("CreateEntity", entity, systemCredentials)}
}

func (_c *EntityProviderInterfaceMock_CreateEntity_Call) Run(run func(entity *entityprovider.Entity, systemCredentials json.RawMessage)) *EntityProviderInterfaceMock_CreateEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *entityprovider.Entity
		if args[0] != nil {
			arg0 = args[0].(*entityprovider.Entity)
		}
		var arg1 json.RawMessage
		if args[1] != nil {
			arg1 = args[1].(json.RawMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EntityProviderInterfaceMock_CreateEntity_Call) Return(entity1 *entityprovider.Entity, entityProviderError *entityprovider.EntityProviderError) *EntityProviderInterfaceMock_CreateEntity_Call {
	_c.Call.Return(entity1, entityProviderError)
	return _c
}

func (_c *EntityProviderInterfaceMock_CreateEntity_Call) RunAndReturn(run func(entity *entityprovider.Entity, systemCredentials json.RawMessage) (*entityprovider.Entity, *entityprovider.EntityProviderError)) *EntityProviderInterfaceMock_CreateEntity_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEntity provides a mock function for the type EntityProviderInterfaceMock
func (_mock *EntityProviderInterfaceMock) DeleteEntity(entityID string) *entityprovider.EntityProviderError {
	ret := _mock.Called(entityID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEntity")
	}

	var r0 *entityprovider.EntityProviderError
	if returnFunc, ok := ret.Get(0).(func(string) *entityprovider.EntityProviderError); ok {
		r0 = returnFunc(entityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entityprovider.EntityProviderError)
		}
	}
	return r0
}

// EntityProviderInterfaceMock_DeleteEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEntity'
type EntityProviderInterfaceMock_DeleteEntity_Call struct {
	*mock.Call
}

// DeleteEntity is a helper method to define mock.On call
//   - entityID string
func (_e *EntityProviderInterfaceMock_Expecter) DeleteEntity(entityID interface{}) *EntityProviderInterfaceMock_DeleteEntity_Call {
	return &EntityProviderInterfaceMock_DeleteEntity_Call{Call: _e.mock.On("DeleteEntity", entityID)}
}

func (_c *EntityProviderInterfaceMock_DeleteEntity_Call) Run(run func(entityID string)) *EntityProviderInterfaceMock_DeleteEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EntityProviderInterfaceMock_DeleteEntity_Call) Return(entityProviderError *entityprovider.EntityProviderError) *EntityProviderInterfaceMock_DeleteEntity_Call {
	_c.Call.Return(entityProviderError)
	return _c
}

func (_c *EntityProviderInterfaceMock_DeleteEntity_Call) RunAndReturn(run func(entityID string) *entityprovider.EntityProviderError) *EntityProviderInterfaceMock_DeleteEntity_Call {
	_c.Call.Return(run)
	return _c
}

// GetEntitiesByIDs provides a mock function for the type EntityProviderInterfaceMock
func (_mock *EntityProviderInterfaceMock) GetEntitiesByIDs(entityIDs []string) ([]entityprovider.Entity, *entityprovider.EntityProviderError) {
	ret := _mock.Called(entityIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetEntitiesByIDs")
	}

	var r0 []entityprovider.Entity
	var r1 *entityprovider.EntityProviderError
	if returnFunc, ok := ret.Get(0).(func([]string) ([]entityprovider.Entity, *entityprovider.EntityProviderError)); ok {
		return returnFunc(entityIDs)
	}
	if returnFunc, ok := ret.Get(0).(func([]string) []entityprovider.Entity); ok {
		r0 = returnFunc(entityIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entityprovider.Entity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]string) *entityprovider.EntityProviderError); ok {
		r1 = returnFunc(entityIDs)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entityprovider.EntityProviderError)
		}
	}
	return r0, r1
}

// EntityProviderInterfaceMock_GetEntitiesByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntitiesByIDs'
type EntityProviderInterfaceMock_GetEntitiesByIDs_Call struct {
	*mock.Call
}

// GetEntitiesByIDs is a helper method to define mock.On call
//   - entityIDs []string
func (_e *EntityProviderInterfaceMock_Expecter) GetEntitiesByIDs(entityIDs interface{}) *EntityProviderInterfaceMock_GetEntitiesByIDs_Call {
	return &EntityProviderInterfaceMock_GetEntitiesByIDs_Call{Call: _e.mock.On("GetEntitiesByIDs", entityIDs)}
}

func (_c *EntityProviderInterfaceMock_GetEntitiesByIDs_Call) Run(run func(entityIDs []string)) *EntityProviderInterfaceMock_GetEntitiesByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EntityProviderInterfaceMock_GetEntitiesByIDs_Call) Return(entitys []entityprovider.Entity, entityProviderError *entityprovider.EntityProviderError) *EntityProviderInterfaceMock_GetEntitiesByIDs_Call {
	_c.Call.Return(entitys, entityProviderError)
	return _c
}

func (_c *EntityProviderInterfaceMock_GetEntitiesByIDs_Call) RunAndReturn(run func(entityIDs []string) ([]entityprovider.Entity, *entityprovider.EntityProviderError)) *EntityProviderInterfaceMock_GetEntitiesByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetEntity provides a mock function for the type EntityProviderInterfaceMock
func (_mock *EntityProviderInterfaceMock) GetEntity(entityID string) (*entityprovider.Entity, *entityprovider.EntityProviderError) {
	ret := _mock.Called(entityID)

	if len(ret) == 0 {
		panic("no return value specified for GetEntity")
	}

	var r0 *entityprovider.Entity
	var r1 *entityprovider.EntityProviderError
	if returnFunc, ok := ret.Get(0).(func(string) (*entityprovider.Entity, *entityprovider.EntityProviderError)); ok {
		return returnFunc(entityID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *entityprovider.Entity); ok {
		r0 = returnFunc(entityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entityprovider.Entity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *entityprovider.EntityProviderError); ok {
		r1 = returnFunc(entityID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entityprovider.EntityProviderError)
		}
	}
	return r0, r1
}

// EntityProviderInterfaceMock_GetEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntity'
type EntityProviderInterfaceMock_GetEntity_Call struct {
	*mock.Call
}

// GetEntity is a helper method to define mock.On call
//   - entityID string
func (_e *EntityProviderInterfaceMock_Expecter) GetEntity(entityID interface{}) *EntityProviderInterfaceMock_GetEntity_Call {
	return &EntityProviderInterfaceMock_GetEntity_Call{Call: _e.mock.On("GetEntity", entityID)}
}

func (_c *EntityProviderInterfaceMock_GetEntity_Call) Run(run func(entityID string)) *EntityProviderInterfaceMock_GetEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EntityProviderInterfaceMock_GetEntity_Call) Return(entity *entityprovider.Entity, entityProviderError *entityprovider.EntityProviderError) *EntityProviderInterfaceMock_GetEntity_Call {
	_c.Call.Return(entity, entityProviderError)
	return _c
}

func (_c *EntityProviderInterfaceMock_GetEntity_Call) RunAndReturn(run func(entityID string) (*entityprovider.Entity, *entityprovider.EntityProviderError)) *EntityProviderInterfaceMock_GetEntity_Call {
	_c.Call.Return(run)
	return _c
}

// GetEntityGroups provides a mock function for the type EntityProviderInterfaceMock
func (_mock *EntityProviderInterfaceMock) GetEntityGroups(entityID string, limit int, offset int) (*entityprovider.EntityGroupListResponse, *entityprovider.EntityProviderError) {
	ret := _mock.Called(entityID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetEntityGroups")
	}

	var r0 *entityprovider.EntityGroupListResponse
	var r1 *entityprovider.EntityProviderError
	if returnFunc, ok := ret.Get(0).(func(string, int, int) (*entityprovider.EntityGroupListResponse, *entityprovider.EntityProviderError)); ok {
		return returnFunc(entityID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int, int) *entityprovider.EntityGroupListResponse); ok {
		r0 = returnFunc(entityID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entityprovider.EntityGroupListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int, int) *entityprovider.EntityProviderError); ok {
		r1 = returnFunc(entityID, limit, offset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entityprovider.EntityProviderError)
		}
	}
	return r0, r1
}

// EntityProviderInterfaceMock_GetEntityGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntityGroups'
type EntityProviderInterfaceMock_GetEntityGroups_Call struct {
	*mock.Call
}

// GetEntityGroups is a helper method to define mock.On call
//   - entityID string
//   - limit int
//   - offset int
func (_e *EntityProviderInterfaceMock_Expecter) GetEntityGroups(entityID interface{}, limit interface{}, offset interface{}) *EntityProviderInterfaceMock_GetEntityGroups_Call {
	return &EntityProviderInterfaceMock_GetEntityGroups_Call{Call: _e.mock.On("GetEntityGroups", entityID, limit, offset)}
}

func (_c *EntityProviderInterfaceMock_GetEntityGroups_Call) Run(run func(entityID string, limit int, offset int)) *EntityProviderInterfaceMock_GetEntityGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EntityProviderInterfaceMock_GetEntityGroups_Call) Return(entityGroupListResponse *entityprovider.EntityGroupListResponse, entityProviderError *entityprovider.EntityProviderError) *EntityProviderInterfaceMock_GetEntityGroups_Call {
	_c.Call.Return(entityGroupListResponse, entityProviderError)
	return _c
}

func (_c *EntityProviderInterfaceMock_GetEntityGroups_Call) RunAndReturn(run func(entityID string, limit int, offset int) (*entityprovider.EntityGroupListResponse, *entityprovider.EntityProviderError)) *EntityProviderInterfaceMock_GetEntityGroups_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransitiveEntityGroups provides a mock function for the type EntityProviderInterfaceMock
func (_mock *EntityProviderInterfaceMock) GetTransitiveEntityGroups(entityID string) ([]entityprovider.EntityGroup, *entityprovider.EntityProviderError) {
	ret := _mock.Called(entityID)

	if len(ret) == 0 {
		panic("no return value specified for GetTransitiveEntityGroups")
	}

	var r0 []entityprovider.EntityGroup
	var r1 *entityprovider.EntityProviderError
	if returnFunc, ok := ret.Get(0).(func(string) ([]entityprovider.EntityGroup, *entityprovider.EntityProviderError)); ok {
		return returnFunc(entityID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []entityprovider.EntityGroup); ok {
		r0 = returnFunc(entityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entityprovider.EntityGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *entityprovider.EntityProviderError); ok {
		r1 = returnFunc(entityID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entityprovider.EntityProviderError)
		}
	}
	return r0, r1
}

// EntityProviderInterfaceMock_GetTransitiveEntityGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransitiveEntityGroups'
type EntityProviderInterfaceMock_GetTransitiveEntityGroups_Call struct {
	*mock.Call
}

// GetTransitiveEntityGroups is a helper method to define mock.On call
//   - entityID string
func (_e *EntityProviderInterfaceMock_Expecter) GetTransitiveEntityGroups(entityID interface{}) *EntityProviderInterfaceMock_GetTransitiveEntityGroups_Call {
	return &EntityProviderInterfaceMock_GetTransitiveEntityGroups_Call{Call: _e.mock.On("GetTransitiveEntityGroups", entityID)}
}

func (_c *EntityProviderInterfaceMock_GetTransitiveEntityGroups_Call) Run(run func(entityID string)) *EntityProviderInterfaceMock_GetTransitiveEntityGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EntityProviderInterfaceMock_GetTransitiveEntityGroups_Call) Return(entityGroups []entityprovider.EntityGroup, entityProviderError *entityprovider.EntityProviderError) *EntityProviderInterfaceMock_GetTransitiveEntityGroups_Call {
	_c.Call.Return(entityGroups, entityProviderError)
	return _c
}

func (_c *EntityProviderInterfaceMock_GetTransitiveEntityGroups_Call) RunAndReturn(run func(entityID string) ([]entityprovider.EntityGroup, *entityprovider.EntityProviderError)) *EntityProviderInterfaceMock_GetTransitiveEntityGroups_Call {
	_c.Call.Return(run)
	return _c
}

// IdentifyEntity provides a mock function for the type EntityProviderInterfaceMock
func (_mock *EntityProviderInterfaceMock) IdentifyEntity(filters map[string]interface{}) (*string, *entityprovider.EntityProviderError) {
	ret := _mock.Called(filters)

	if len(ret) == 0 {
		panic("no return value specified for IdentifyEntity")
	}

	var r0 *string
	var r1 *entityprovider.EntityProviderError
	if returnFunc, ok := ret.Get(0).(func(map[string]interface{}) (*string, *entityprovider.EntityProviderError)); ok {
		return returnFunc(filters)
	}
	if returnFunc, ok := ret.Get(0).(func(map[string]interface{}) *string); ok {
		r0 = returnFunc(filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(map[string]interface{}) *entityprovider.EntityProviderError); ok {
		r1 = returnFunc(filters)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entityprovider.EntityProviderError)
		}
	}
	return r0, r1
}

// EntityProviderInterfaceMock_IdentifyEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IdentifyEntity'
type EntityProviderInterfaceMock_IdentifyEntity_Call struct {
	*mock.Call
}

// IdentifyEntity is a helper method to define mock.On call
//   - filters map[string]interface{}
func (_e *EntityProviderInterfaceMock_Expecter) IdentifyEntity(filters interface{}) *EntityProviderInterfaceMock_IdentifyEntity_Call {
	return &EntityProviderInterfaceMock_IdentifyEntity_Call{Call: _e.mock.On("IdentifyEntity", filters)}
}

func (_c *EntityProviderInterfaceMock_IdentifyEntity_Call) Run(run func(filters map[string]interface{})) *EntityProviderInterfaceMock_IdentifyEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]interface{}
		if args[0] != nil {
			arg0 = args[0].(map[string]interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EntityProviderInterfaceMock_IdentifyEntity_Call) Return(s *string, entityProviderError *entityprovider.EntityProviderError) *EntityProviderInterfaceMock_IdentifyEntity_Call {
	_c.Call.Return(s, entityProviderError)
	return _c
}

func (_c *EntityProviderInterfaceMock_IdentifyEntity_Call) RunAndReturn(run func(filters map[string]interface{}) (*string, *entityprovider.EntityProviderError)) *EntityProviderInterfaceMock_IdentifyEntity_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEntity provides a mock function for the type EntityProviderInterfaceMock
func (_mock *EntityProviderInterfaceMock) UpdateEntity(entityID string, entity *entityprovider.Entity) (*entityprovider.Entity, *entityprovider.EntityProviderError) {
	ret := _mock.Called(entityID, entity)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEntity")
	}

	var r0 *entityprovider.Entity
	var r1 *entityprovider.EntityProviderError
	if returnFunc, ok := ret.Get(0).(func(string, *entityprovider.Entity) (*entityprovider.Entity, *entityprovider.EntityProviderError)); ok {
		return returnFunc(entityID, entity)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *entityprovider.Entity) *entityprovider.Entity); ok {
		r0 = returnFunc(entityID, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entityprovider.Entity)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *entityprovider.Entity) *entityprovider.EntityProviderError); ok {
		r1 = returnFunc(entityID, entity)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entityprovider.EntityProviderError)
		}
	}
	return r0, r1
}

// EntityProviderInterfaceMock_UpdateEntity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEntity'
type EntityProviderInterfaceMock_UpdateEntity_Call struct {
	*mock.Call
}

// UpdateEntity is a helper method to define mock.On call
//   - entityID string
//   - entity *entityprovider.Entity
func (_e *EntityProviderInterfaceMock_Expecter) UpdateEntity(entityID interface{}, entity interface{}) *EntityProviderInterfaceMock_UpdateEntity_Call {
	return &EntityProviderInterfaceMock_UpdateEntity_Call{Call: _e.mock.On("UpdateEntity", entityID, entity)}
}

func (_c *EntityProviderInterfaceMock_UpdateEntity_Call) Run(run func(entityID string, entity *entityprovider.Entity)) *EntityProviderInterfaceMock_UpdateEntity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *entityprovider.Entity
		if args[1] != nil {
			arg1 = args[1].(*entityprovider.Entity)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EntityProviderInterfaceMock_UpdateEntity_Call) Return(entity1 *entityprovider.Entity, entityProviderError *entityprovider.EntityProviderError) *EntityProviderInterfaceMock_UpdateEntity_Call {
	_c.Call.Return(entity1, entityProviderError)
	return _c
}

func (_c *EntityProviderInterfaceMock_UpdateEntity_Call) RunAndReturn(run func(entityID string, entity *entityprovider.Entity) (*entityprovider.Entity, *entityprovider.EntityProviderError)) *EntityProviderInterfaceMock_UpdateEntity_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSystemAttributes provides a mock function for the type EntityProviderInterfaceMock
func (_mock *EntityProviderInterfaceMock) UpdateSystemAttributes(entityID string, attributes json.RawMessage) *entityprovider.EntityProviderError {
	ret := _mock.Called(entityID, attributes)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSystemAttributes")
	}

	var r0 *entityprovider.EntityProviderError
	if returnFunc, ok := ret.Get(0).(func(string, json.RawMessage) *entityprovider.EntityProviderError); ok {
		r0 = returnFunc(entityID, attributes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entityprovider.EntityProviderError)
		}
	}
	return r0
}

// EntityProviderInterfaceMock_UpdateSystemAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSystemAttributes'
type EntityProviderInterfaceMock_UpdateSystemAttributes_Call struct {
	*mock.Call
}

// UpdateSystemAttributes is a helper method to define mock.On call
//   - entityID string
//   - attributes json.RawMessage
func (_e *EntityProviderInterfaceMock_Expecter) UpdateSystemAttributes(entityID interface{}, attributes interface{}) *EntityProviderInterfaceMock_UpdateSystemAttributes_Call {
	return &EntityProviderInterfaceMock_UpdateSystemAttributes_Call{Call: _e.mock.On("UpdateSystemAttributes", entityID, attributes)}
}

func (_c *EntityProviderInterfaceMock_UpdateSystemAttributes_Call) Run(run func(entityID string, attributes json.RawMessage)) *EntityProviderInterfaceMock_UpdateSystemAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 json.RawMessage
		if args[1] != nil {
			arg1 = args[1].(json.RawMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EntityProviderInterfaceMock_UpdateSystemAttributes_Call) Return(entityProviderError *entityprovider.EntityProviderError) *EntityProviderInterfaceMock_UpdateSystemAttributes_Call {
	_c.Call.Return(entityProviderError)
	return _c
}

func (_c *EntityProviderInterfaceMock_UpdateSystemAttributes_Call) RunAndReturn(run func(entityID string, attributes json.RawMessage) *entityprovider.EntityProviderError) *EntityProviderInterfaceMock_UpdateSystemAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSystemCredentials provides a mock function for the type EntityProviderInterfaceMock
func (_mock *EntityProviderInterfaceMock) UpdateSystemCredentials(entityID string, credentials json.RawMessage) *entityprovider.EntityProviderError {
	ret := _mock.Called(entityID, credentials)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSystemCredentials")
	}

	var r0 *entityprovider.EntityProviderError
	if returnFunc, ok := ret.Get(0).(func(string, json.RawMessage) *entityprovider.EntityProviderError); ok {
		r0 = returnFunc(entityID, credentials)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entityprovider.EntityProviderError)
		}
	}
	return r0
}

// EntityProviderInterfaceMock_UpdateSystemCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSystemCredentials'
type EntityProviderInterfaceMock_UpdateSystemCredentials_Call struct {
	*mock.Call
}

// UpdateSystemCredentials is a helper method to define mock.On call
//   - entityID string
//   - credentials json.RawMessage
func (_e *EntityProviderInterfaceMock_Expecter) UpdateSystemCredentials(entityID interface{}, credentials interface{}) *EntityProviderInterfaceMock_UpdateSystemCredentials_Call {
	return &EntityProviderInterfaceMock_UpdateSystemCredentials_Call{Call: _e.mock.On("UpdateSystemCredentials", entityID, credentials)}
}

func (_c *EntityProviderInterfaceMock_UpdateSystemCredentials_Call) Run(run func(entityID string, credentials json.RawMessage)) *EntityProviderInterfaceMock_UpdateSystemCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 json.RawMessage
		if args[1] != nil {
			arg1 = args[1].(json.RawMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EntityProviderInterfaceMock_UpdateSystemCredentials_Call) Return(entityProviderError *entityprovider.EntityProviderError) *EntityProviderInterfaceMock_UpdateSystemCredentials_Call {
	_c.Call.Return(entityProviderError)
	return _c
}

func (_c *EntityProviderInterfaceMock_UpdateSystemCredentials_Call) RunAndReturn(run func(entityID string, credentials json.RawMessage) *entityprovider.EntityProviderError) *EntityProviderInterfaceMock_UpdateSystemCredentials_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateEntityIDs provides a mock function for the type EntityProviderInterfaceMock
func (_mock *EntityProviderInterfaceMock) ValidateEntityIDs(entityIDs []string) ([]string, *entityprovider.EntityProviderError) {
	ret := _mock.Called(entityIDs)

	if len(ret) == 0 {
		panic("no return value specified for ValidateEntityIDs")
	}

	var r0 []string
	var r1 *entityprovider.EntityProviderError
	if returnFunc, ok := ret.Get(0).(func([]string) ([]string, *entityprovider.EntityProviderError)); ok {
		return returnFunc(entityIDs)
	}
	if returnFunc, ok := ret.Get(0).(func([]string) []string); ok {
		r0 = returnFunc(entityIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]string) *entityprovider.EntityProviderError); ok {
		r1 = returnFunc(entityIDs)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entityprovider.EntityProviderError)
		}
	}
	return r0, r1
}

// EntityProviderInterfaceMock_ValidateEntityIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateEntityIDs'
type EntityProviderInterfaceMock_ValidateEntityIDs_Call struct {
	*mock.Call
}

// ValidateEntityIDs is a helper method to define mock.On call
//   - entityIDs []string
func (_e *EntityProviderInterfaceMock_Expecter) ValidateEntityIDs(entityIDs interface{}) *EntityProviderInterfaceMock_ValidateEntityIDs_Call {
	return &EntityProviderInterfaceMock_ValidateEntityIDs_Call{Call: _e.mock.On("ValidateEntityIDs", entityIDs)}
}

func (_c *EntityProviderInterfaceMock_ValidateEntityIDs_Call) Run(run func(entityIDs []string)) *EntityProviderInterfaceMock_ValidateEntityIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *EntityProviderInterfaceMock_ValidateEntityIDs_Call) Return(strings []string, entityProviderError *entityprovider.EntityProviderError) *EntityProviderInterfaceMock_ValidateEntityIDs_Call {
	_c.Call.Return(strings, entityProviderError)
	return _c
}

func (_c *EntityProviderInterfaceMock_ValidateEntityIDs_Call) RunAndReturn(run func(entityIDs []string) ([]string, *entityprovider.EntityProviderError)) *EntityProviderInterfaceMock_ValidateEntityIDs_Call {
	_c.Call.Return(run)
	return _c
}
