// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package userprovidermock

import (
	"encoding/json"

	"github.com/asgardeo/thunder/internal/userprovider"
	mock "github.com/stretchr/testify/mock"
)

// NewUserProviderInterfaceMock creates a new instance of UserProviderInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserProviderInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserProviderInterfaceMock {
	mock := &UserProviderInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserProviderInterfaceMock is an autogenerated mock type for the UserProviderInterface type
type UserProviderInterfaceMock struct {
	mock.Mock
}

type UserProviderInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserProviderInterfaceMock) EXPECT() *UserProviderInterfaceMock_Expecter {
	return &UserProviderInterfaceMock_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type UserProviderInterfaceMock
func (_mock *UserProviderInterfaceMock) CreateUser(user *userprovider.User) (*userprovider.User, *userprovider.UserProviderError) {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *userprovider.User
	var r1 *userprovider.UserProviderError
	if returnFunc, ok := ret.Get(0).(func(*userprovider.User) (*userprovider.User, *userprovider.UserProviderError)); ok {
		return returnFunc(user)
	}
	if returnFunc, ok := ret.Get(0).(func(*userprovider.User) *userprovider.User); ok {
		r0 = returnFunc(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userprovider.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*userprovider.User) *userprovider.UserProviderError); ok {
		r1 = returnFunc(user)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*userprovider.UserProviderError)
		}
	}
	return r0, r1
}

// UserProviderInterfaceMock_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type UserProviderInterfaceMock_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - user *userprovider.User
func (_e *UserProviderInterfaceMock_Expecter) CreateUser(user interface{}) *UserProviderInterfaceMock_CreateUser_Call {
	return &UserProviderInterfaceMock_CreateUser_Call{Call: _e.mock.On("CreateUser", user)}
}

func (_c *UserProviderInterfaceMock_CreateUser_Call) Run(run func(user *userprovider.User)) *UserProviderInterfaceMock_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *userprovider.User
		if args[0] != nil {
			arg0 = args[0].(*userprovider.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserProviderInterfaceMock_CreateUser_Call) Return(user1 *userprovider.User, userProviderError *userprovider.UserProviderError) *UserProviderInterfaceMock_CreateUser_Call {
	_c.Call.Return(user1, userProviderError)
	return _c
}

func (_c *UserProviderInterfaceMock_CreateUser_Call) RunAndReturn(run func(user *userprovider.User) (*userprovider.User, *userprovider.UserProviderError)) *UserProviderInterfaceMock_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUser provides a mock function for the type UserProviderInterfaceMock
func (_mock *UserProviderInterfaceMock) DeleteUser(userID string) *userprovider.UserProviderError {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 *userprovider.UserProviderError
	if returnFunc, ok := ret.Get(0).(func(string) *userprovider.UserProviderError); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userprovider.UserProviderError)
		}
	}
	return r0
}

// UserProviderInterfaceMock_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type UserProviderInterfaceMock_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - userID string
func (_e *UserProviderInterfaceMock_Expecter) DeleteUser(userID interface{}) *UserProviderInterfaceMock_DeleteUser_Call {
	return &UserProviderInterfaceMock_DeleteUser_Call{Call: _e.mock.On("DeleteUser", userID)}
}

func (_c *UserProviderInterfaceMock_DeleteUser_Call) Run(run func(userID string)) *UserProviderInterfaceMock_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserProviderInterfaceMock_DeleteUser_Call) Return(userProviderError *userprovider.UserProviderError) *UserProviderInterfaceMock_DeleteUser_Call {
	_c.Call.Return(userProviderError)
	return _c
}

func (_c *UserProviderInterfaceMock_DeleteUser_Call) RunAndReturn(run func(userID string) *userprovider.UserProviderError) *UserProviderInterfaceMock_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetTransitiveUserGroups provides a mock function for the type UserProviderInterfaceMock
func (_mock *UserProviderInterfaceMock) GetTransitiveUserGroups(userID string) ([]userprovider.UserGroup, *userprovider.UserProviderError) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTransitiveUserGroups")
	}

	var r0 []userprovider.UserGroup
	var r1 *userprovider.UserProviderError
	if returnFunc, ok := ret.Get(0).(func(string) ([]userprovider.UserGroup, *userprovider.UserProviderError)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []userprovider.UserGroup); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]userprovider.UserGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *userprovider.UserProviderError); ok {
		r1 = returnFunc(userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*userprovider.UserProviderError)
		}
	}
	return r0, r1
}

// UserProviderInterfaceMock_GetTransitiveUserGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTransitiveUserGroups'
type UserProviderInterfaceMock_GetTransitiveUserGroups_Call struct {
	*mock.Call
}

// GetTransitiveUserGroups is a helper method to define mock.On call
//   - userID string
func (_e *UserProviderInterfaceMock_Expecter) GetTransitiveUserGroups(userID interface{}) *UserProviderInterfaceMock_GetTransitiveUserGroups_Call {
	return &UserProviderInterfaceMock_GetTransitiveUserGroups_Call{Call: _e.mock.On("GetTransitiveUserGroups", userID)}
}

func (_c *UserProviderInterfaceMock_GetTransitiveUserGroups_Call) Run(run func(userID string)) *UserProviderInterfaceMock_GetTransitiveUserGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserProviderInterfaceMock_GetTransitiveUserGroups_Call) Return(userGroups []userprovider.UserGroup, userProviderError *userprovider.UserProviderError) *UserProviderInterfaceMock_GetTransitiveUserGroups_Call {
	_c.Call.Return(userGroups, userProviderError)
	return _c
}

func (_c *UserProviderInterfaceMock_GetTransitiveUserGroups_Call) RunAndReturn(run func(userID string) ([]userprovider.UserGroup, *userprovider.UserProviderError)) *UserProviderInterfaceMock_GetTransitiveUserGroups_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type UserProviderInterfaceMock
func (_mock *UserProviderInterfaceMock) GetUser(userID string) (*userprovider.User, *userprovider.UserProviderError) {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *userprovider.User
	var r1 *userprovider.UserProviderError
	if returnFunc, ok := ret.Get(0).(func(string) (*userprovider.User, *userprovider.UserProviderError)); ok {
		return returnFunc(userID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *userprovider.User); ok {
		r0 = returnFunc(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userprovider.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *userprovider.UserProviderError); ok {
		r1 = returnFunc(userID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*userprovider.UserProviderError)
		}
	}
	return r0, r1
}

// UserProviderInterfaceMock_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type UserProviderInterfaceMock_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - userID string
func (_e *UserProviderInterfaceMock_Expecter) GetUser(userID interface{}) *UserProviderInterfaceMock_GetUser_Call {
	return &UserProviderInterfaceMock_GetUser_Call{Call: _e.mock.On("GetUser", userID)}
}

func (_c *UserProviderInterfaceMock_GetUser_Call) Run(run func(userID string)) *UserProviderInterfaceMock_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserProviderInterfaceMock_GetUser_Call) Return(user *userprovider.User, userProviderError *userprovider.UserProviderError) *UserProviderInterfaceMock_GetUser_Call {
	_c.Call.Return(user, userProviderError)
	return _c
}

func (_c *UserProviderInterfaceMock_GetUser_Call) RunAndReturn(run func(userID string) (*userprovider.User, *userprovider.UserProviderError)) *UserProviderInterfaceMock_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserGroups provides a mock function for the type UserProviderInterfaceMock
func (_mock *UserProviderInterfaceMock) GetUserGroups(userID string, limit int, offset int) (*userprovider.UserGroupListResponse, *userprovider.UserProviderError) {
	ret := _mock.Called(userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetUserGroups")
	}

	var r0 *userprovider.UserGroupListResponse
	var r1 *userprovider.UserProviderError
	if returnFunc, ok := ret.Get(0).(func(string, int, int) (*userprovider.UserGroupListResponse, *userprovider.UserProviderError)); ok {
		return returnFunc(userID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int, int) *userprovider.UserGroupListResponse); ok {
		r0 = returnFunc(userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userprovider.UserGroupListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int, int) *userprovider.UserProviderError); ok {
		r1 = returnFunc(userID, limit, offset)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*userprovider.UserProviderError)
		}
	}
	return r0, r1
}

// UserProviderInterfaceMock_GetUserGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserGroups'
type UserProviderInterfaceMock_GetUserGroups_Call struct {
	*mock.Call
}

// GetUserGroups is a helper method to define mock.On call
//   - userID string
//   - limit int
//   - offset int
func (_e *UserProviderInterfaceMock_Expecter) GetUserGroups(userID interface{}, limit interface{}, offset interface{}) *UserProviderInterfaceMock_GetUserGroups_Call {
	return &UserProviderInterfaceMock_GetUserGroups_Call{Call: _e.mock.On("GetUserGroups", userID, limit, offset)}
}

func (_c *UserProviderInterfaceMock_GetUserGroups_Call) Run(run func(userID string, limit int, offset int)) *UserProviderInterfaceMock_GetUserGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserProviderInterfaceMock_GetUserGroups_Call) Return(userGroupListResponse *userprovider.UserGroupListResponse, userProviderError *userprovider.UserProviderError) *UserProviderInterfaceMock_GetUserGroups_Call {
	_c.Call.Return(userGroupListResponse, userProviderError)
	return _c
}

func (_c *UserProviderInterfaceMock_GetUserGroups_Call) RunAndReturn(run func(userID string, limit int, offset int) (*userprovider.UserGroupListResponse, *userprovider.UserProviderError)) *UserProviderInterfaceMock_GetUserGroups_Call {
	_c.Call.Return(run)
	return _c
}

// IdentifyUser provides a mock function for the type UserProviderInterfaceMock
func (_mock *UserProviderInterfaceMock) IdentifyUser(filters map[string]interface{}) (*string, *userprovider.UserProviderError) {
	ret := _mock.Called(filters)

	if len(ret) == 0 {
		panic("no return value specified for IdentifyUser")
	}

	var r0 *string
	var r1 *userprovider.UserProviderError
	if returnFunc, ok := ret.Get(0).(func(map[string]interface{}) (*string, *userprovider.UserProviderError)); ok {
		return returnFunc(filters)
	}
	if returnFunc, ok := ret.Get(0).(func(map[string]interface{}) *string); ok {
		r0 = returnFunc(filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(map[string]interface{}) *userprovider.UserProviderError); ok {
		r1 = returnFunc(filters)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*userprovider.UserProviderError)
		}
	}
	return r0, r1
}

// UserProviderInterfaceMock_IdentifyUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IdentifyUser'
type UserProviderInterfaceMock_IdentifyUser_Call struct {
	*mock.Call
}

// IdentifyUser is a helper method to define mock.On call
//   - filters map[string]interface{}
func (_e *UserProviderInterfaceMock_Expecter) IdentifyUser(filters interface{}) *UserProviderInterfaceMock_IdentifyUser_Call {
	return &UserProviderInterfaceMock_IdentifyUser_Call{Call: _e.mock.On("IdentifyUser", filters)}
}

func (_c *UserProviderInterfaceMock_IdentifyUser_Call) Run(run func(filters map[string]interface{})) *UserProviderInterfaceMock_IdentifyUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]interface{}
		if args[0] != nil {
			arg0 = args[0].(map[string]interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserProviderInterfaceMock_IdentifyUser_Call) Return(s *string, userProviderError *userprovider.UserProviderError) *UserProviderInterfaceMock_IdentifyUser_Call {
	_c.Call.Return(s, userProviderError)
	return _c
}

func (_c *UserProviderInterfaceMock_IdentifyUser_Call) RunAndReturn(run func(filters map[string]interface{}) (*string, *userprovider.UserProviderError)) *UserProviderInterfaceMock_IdentifyUser_Call {
	_c.Call.Return(run)
	return _c
}

// SearchUsers provides a mock function for the type UserProviderInterfaceMock
func (_mock *UserProviderInterfaceMock) SearchUsers(filters map[string]interface{}) ([]*userprovider.User, *userprovider.UserProviderError) {
	ret := _mock.Called(filters)

	if len(ret) == 0 {
		panic("no return value specified for SearchUsers")
	}

	var r0 []*userprovider.User
	var r1 *userprovider.UserProviderError
	if returnFunc, ok := ret.Get(0).(func(map[string]interface{}) ([]*userprovider.User, *userprovider.UserProviderError)); ok {
		return returnFunc(filters)
	}
	if returnFunc, ok := ret.Get(0).(func(map[string]interface{}) []*userprovider.User); ok {
		r0 = returnFunc(filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*userprovider.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(map[string]interface{}) *userprovider.UserProviderError); ok {
		r1 = returnFunc(filters)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*userprovider.UserProviderError)
		}
	}
	return r0, r1
}

// UserProviderInterfaceMock_SearchUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchUsers'
type UserProviderInterfaceMock_SearchUsers_Call struct {
	*mock.Call
}

// SearchUsers is a helper method to define mock.On call
//   - filters map[string]interface{}
func (_e *UserProviderInterfaceMock_Expecter) SearchUsers(filters interface{}) *UserProviderInterfaceMock_SearchUsers_Call {
	return &UserProviderInterfaceMock_SearchUsers_Call{Call: _e.mock.On("SearchUsers", filters)}
}

func (_c *UserProviderInterfaceMock_SearchUsers_Call) Run(run func(filters map[string]interface{})) *UserProviderInterfaceMock_SearchUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]interface{}
		if args[0] != nil {
			arg0 = args[0].(map[string]interface{})
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserProviderInterfaceMock_SearchUsers_Call) Return(users []*userprovider.User, userProviderError *userprovider.UserProviderError) *UserProviderInterfaceMock_SearchUsers_Call {
	_c.Call.Return(users, userProviderError)
	return _c
}

func (_c *UserProviderInterfaceMock_SearchUsers_Call) RunAndReturn(run func(filters map[string]interface{}) ([]*userprovider.User, *userprovider.UserProviderError)) *UserProviderInterfaceMock_SearchUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type UserProviderInterfaceMock
func (_mock *UserProviderInterfaceMock) UpdateUser(userID string, user *userprovider.User) (*userprovider.User, *userprovider.UserProviderError) {
	ret := _mock.Called(userID, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *userprovider.User
	var r1 *userprovider.UserProviderError
	if returnFunc, ok := ret.Get(0).(func(string, *userprovider.User) (*userprovider.User, *userprovider.UserProviderError)); ok {
		return returnFunc(userID, user)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *userprovider.User) *userprovider.User); ok {
		r0 = returnFunc(userID, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userprovider.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *userprovider.User) *userprovider.UserProviderError); ok {
		r1 = returnFunc(userID, user)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*userprovider.UserProviderError)
		}
	}
	return r0, r1
}

// UserProviderInterfaceMock_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type UserProviderInterfaceMock_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - userID string
//   - user *userprovider.User
func (_e *UserProviderInterfaceMock_Expecter) UpdateUser(userID interface{}, user interface{}) *UserProviderInterfaceMock_UpdateUser_Call {
	return &UserProviderInterfaceMock_UpdateUser_Call{Call: _e.mock.On("UpdateUser", userID, user)}
}

func (_c *UserProviderInterfaceMock_UpdateUser_Call) Run(run func(userID string, user *userprovider.User)) *UserProviderInterfaceMock_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *userprovider.User
		if args[1] != nil {
			arg1 = args[1].(*userprovider.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserProviderInterfaceMock_UpdateUser_Call) Return(user1 *userprovider.User, userProviderError *userprovider.UserProviderError) *UserProviderInterfaceMock_UpdateUser_Call {
	_c.Call.Return(user1, userProviderError)
	return _c
}

func (_c *UserProviderInterfaceMock_UpdateUser_Call) RunAndReturn(run func(userID string, user *userprovider.User) (*userprovider.User, *userprovider.UserProviderError)) *UserProviderInterfaceMock_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserCredentials provides a mock function for the type UserProviderInterfaceMock
func (_mock *UserProviderInterfaceMock) UpdateUserCredentials(userID string, credentials json.RawMessage) *userprovider.UserProviderError {
	ret := _mock.Called(userID, credentials)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserCredentials")
	}

	var r0 *userprovider.UserProviderError
	if returnFunc, ok := ret.Get(0).(func(string, json.RawMessage) *userprovider.UserProviderError); ok {
		r0 = returnFunc(userID, credentials)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*userprovider.UserProviderError)
		}
	}
	return r0
}

// UserProviderInterfaceMock_UpdateUserCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserCredentials'
type UserProviderInterfaceMock_UpdateUserCredentials_Call struct {
	*mock.Call
}

// UpdateUserCredentials is a helper method to define mock.On call
//   - userID string
//   - credentials json.RawMessage
func (_e *UserProviderInterfaceMock_Expecter) UpdateUserCredentials(userID interface{}, credentials interface{}) *UserProviderInterfaceMock_UpdateUserCredentials_Call {
	return &UserProviderInterfaceMock_UpdateUserCredentials_Call{Call: _e.mock.On("UpdateUserCredentials", userID, credentials)}
}

func (_c *UserProviderInterfaceMock_UpdateUserCredentials_Call) Run(run func(userID string, credentials json.RawMessage)) *UserProviderInterfaceMock_UpdateUserCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 json.RawMessage
		if args[1] != nil {
			arg1 = args[1].(json.RawMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserProviderInterfaceMock_UpdateUserCredentials_Call) Return(userProviderError *userprovider.UserProviderError) *UserProviderInterfaceMock_UpdateUserCredentials_Call {
	_c.Call.Return(userProviderError)
	return _c
}

func (_c *UserProviderInterfaceMock_UpdateUserCredentials_Call) RunAndReturn(run func(userID string, credentials json.RawMessage) *userprovider.UserProviderError) *UserProviderInterfaceMock_UpdateUserCredentials_Call {
	_c.Call.Return(run)
	return _c
}
