// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package application

import (
	"context"
	"encoding/json"

	mock "github.com/stretchr/testify/mock"
)

// newApplicationStoreInterfaceMock creates a new instance of applicationStoreInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newApplicationStoreInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *applicationStoreInterfaceMock {
	mock := &applicationStoreInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// applicationStoreInterfaceMock is an autogenerated mock type for the applicationStoreInterface type
type applicationStoreInterfaceMock struct {
	mock.Mock
}

type applicationStoreInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *applicationStoreInterfaceMock) EXPECT() *applicationStoreInterfaceMock_Expecter {
	return &applicationStoreInterfaceMock_Expecter{mock: &_m.Mock}
}

// CreateApplication provides a mock function for the type applicationStoreInterfaceMock
func (_mock *applicationStoreInterfaceMock) CreateApplication(ctx context.Context, app applicationConfigDAO) error {
	ret := _mock.Called(ctx, app)

	if len(ret) == 0 {
		panic("no return value specified for CreateApplication")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, applicationConfigDAO) error); ok {
		r0 = returnFunc(ctx, app)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// applicationStoreInterfaceMock_CreateApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateApplication'
type applicationStoreInterfaceMock_CreateApplication_Call struct {
	*mock.Call
}

// CreateApplication is a helper method to define mock.On call
//   - ctx context.Context
//   - app applicationConfigDAO
func (_e *applicationStoreInterfaceMock_Expecter) CreateApplication(ctx interface{}, app interface{}) *applicationStoreInterfaceMock_CreateApplication_Call {
	return &applicationStoreInterfaceMock_CreateApplication_Call{Call: _e.mock.On("CreateApplication", ctx, app)}
}

func (_c *applicationStoreInterfaceMock_CreateApplication_Call) Run(run func(ctx context.Context, app applicationConfigDAO)) *applicationStoreInterfaceMock_CreateApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 applicationConfigDAO
		if args[1] != nil {
			arg1 = args[1].(applicationConfigDAO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *applicationStoreInterfaceMock_CreateApplication_Call) Return(err error) *applicationStoreInterfaceMock_CreateApplication_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *applicationStoreInterfaceMock_CreateApplication_Call) RunAndReturn(run func(ctx context.Context, app applicationConfigDAO) error) *applicationStoreInterfaceMock_CreateApplication_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOAuthConfig provides a mock function for the type applicationStoreInterfaceMock
func (_mock *applicationStoreInterfaceMock) CreateOAuthConfig(ctx context.Context, entityID string, oauthConfigJSON json.RawMessage) error {
	ret := _mock.Called(ctx, entityID, oauthConfigJSON)

	if len(ret) == 0 {
		panic("no return value specified for CreateOAuthConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, json.RawMessage) error); ok {
		r0 = returnFunc(ctx, entityID, oauthConfigJSON)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// applicationStoreInterfaceMock_CreateOAuthConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOAuthConfig'
type applicationStoreInterfaceMock_CreateOAuthConfig_Call struct {
	*mock.Call
}

// CreateOAuthConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID string
//   - oauthConfigJSON json.RawMessage
func (_e *applicationStoreInterfaceMock_Expecter) CreateOAuthConfig(ctx interface{}, entityID interface{}, oauthConfigJSON interface{}) *applicationStoreInterfaceMock_CreateOAuthConfig_Call {
	return &applicationStoreInterfaceMock_CreateOAuthConfig_Call{Call: _e.mock.On("CreateOAuthConfig", ctx, entityID, oauthConfigJSON)}
}

func (_c *applicationStoreInterfaceMock_CreateOAuthConfig_Call) Run(run func(ctx context.Context, entityID string, oauthConfigJSON json.RawMessage)) *applicationStoreInterfaceMock_CreateOAuthConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 json.RawMessage
		if args[2] != nil {
			arg2 = args[2].(json.RawMessage)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *applicationStoreInterfaceMock_CreateOAuthConfig_Call) Return(err error) *applicationStoreInterfaceMock_CreateOAuthConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *applicationStoreInterfaceMock_CreateOAuthConfig_Call) RunAndReturn(run func(ctx context.Context, entityID string, oauthConfigJSON json.RawMessage) error) *applicationStoreInterfaceMock_CreateOAuthConfig_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteApplication provides a mock function for the type applicationStoreInterfaceMock
func (_mock *applicationStoreInterfaceMock) DeleteApplication(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteApplication")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// applicationStoreInterfaceMock_DeleteApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteApplication'
type applicationStoreInterfaceMock_DeleteApplication_Call struct {
	*mock.Call
}

// DeleteApplication is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *applicationStoreInterfaceMock_Expecter) DeleteApplication(ctx interface{}, id interface{}) *applicationStoreInterfaceMock_DeleteApplication_Call {
	return &applicationStoreInterfaceMock_DeleteApplication_Call{Call: _e.mock.On("DeleteApplication", ctx, id)}
}

func (_c *applicationStoreInterfaceMock_DeleteApplication_Call) Run(run func(ctx context.Context, id string)) *applicationStoreInterfaceMock_DeleteApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *applicationStoreInterfaceMock_DeleteApplication_Call) Return(err error) *applicationStoreInterfaceMock_DeleteApplication_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *applicationStoreInterfaceMock_DeleteApplication_Call) RunAndReturn(run func(ctx context.Context, id string) error) *applicationStoreInterfaceMock_DeleteApplication_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOAuthConfig provides a mock function for the type applicationStoreInterfaceMock
func (_mock *applicationStoreInterfaceMock) DeleteOAuthConfig(ctx context.Context, entityID string) error {
	ret := _mock.Called(ctx, entityID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOAuthConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, entityID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// applicationStoreInterfaceMock_DeleteOAuthConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOAuthConfig'
type applicationStoreInterfaceMock_DeleteOAuthConfig_Call struct {
	*mock.Call
}

// DeleteOAuthConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID string
func (_e *applicationStoreInterfaceMock_Expecter) DeleteOAuthConfig(ctx interface{}, entityID interface{}) *applicationStoreInterfaceMock_DeleteOAuthConfig_Call {
	return &applicationStoreInterfaceMock_DeleteOAuthConfig_Call{Call: _e.mock.On("DeleteOAuthConfig", ctx, entityID)}
}

func (_c *applicationStoreInterfaceMock_DeleteOAuthConfig_Call) Run(run func(ctx context.Context, entityID string)) *applicationStoreInterfaceMock_DeleteOAuthConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *applicationStoreInterfaceMock_DeleteOAuthConfig_Call) Return(err error) *applicationStoreInterfaceMock_DeleteOAuthConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *applicationStoreInterfaceMock_DeleteOAuthConfig_Call) RunAndReturn(run func(ctx context.Context, entityID string) error) *applicationStoreInterfaceMock_DeleteOAuthConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetApplicationByID provides a mock function for the type applicationStoreInterfaceMock
func (_mock *applicationStoreInterfaceMock) GetApplicationByID(ctx context.Context, id string) (*applicationConfigDAO, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetApplicationByID")
	}

	var r0 *applicationConfigDAO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*applicationConfigDAO, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *applicationConfigDAO); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*applicationConfigDAO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// applicationStoreInterfaceMock_GetApplicationByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApplicationByID'
type applicationStoreInterfaceMock_GetApplicationByID_Call struct {
	*mock.Call
}

// GetApplicationByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *applicationStoreInterfaceMock_Expecter) GetApplicationByID(ctx interface{}, id interface{}) *applicationStoreInterfaceMock_GetApplicationByID_Call {
	return &applicationStoreInterfaceMock_GetApplicationByID_Call{Call: _e.mock.On("GetApplicationByID", ctx, id)}
}

func (_c *applicationStoreInterfaceMock_GetApplicationByID_Call) Run(run func(ctx context.Context, id string)) *applicationStoreInterfaceMock_GetApplicationByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *applicationStoreInterfaceMock_GetApplicationByID_Call) Return(applicationConfigDAOMoqParam *applicationConfigDAO, err error) *applicationStoreInterfaceMock_GetApplicationByID_Call {
	_c.Call.Return(applicationConfigDAOMoqParam, err)
	return _c
}

func (_c *applicationStoreInterfaceMock_GetApplicationByID_Call) RunAndReturn(run func(ctx context.Context, id string) (*applicationConfigDAO, error)) *applicationStoreInterfaceMock_GetApplicationByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetApplicationList provides a mock function for the type applicationStoreInterfaceMock
func (_mock *applicationStoreInterfaceMock) GetApplicationList(ctx context.Context) ([]applicationConfigDAO, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetApplicationList")
	}

	var r0 []applicationConfigDAO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]applicationConfigDAO, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []applicationConfigDAO); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]applicationConfigDAO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// applicationStoreInterfaceMock_GetApplicationList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApplicationList'
type applicationStoreInterfaceMock_GetApplicationList_Call struct {
	*mock.Call
}

// GetApplicationList is a helper method to define mock.On call
//   - ctx context.Context
func (_e *applicationStoreInterfaceMock_Expecter) GetApplicationList(ctx interface{}) *applicationStoreInterfaceMock_GetApplicationList_Call {
	return &applicationStoreInterfaceMock_GetApplicationList_Call{Call: _e.mock.On("GetApplicationList", ctx)}
}

func (_c *applicationStoreInterfaceMock_GetApplicationList_Call) Run(run func(ctx context.Context)) *applicationStoreInterfaceMock_GetApplicationList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *applicationStoreInterfaceMock_GetApplicationList_Call) Return(applicationConfigDAOMoqParams []applicationConfigDAO, err error) *applicationStoreInterfaceMock_GetApplicationList_Call {
	_c.Call.Return(applicationConfigDAOMoqParams, err)
	return _c
}

func (_c *applicationStoreInterfaceMock_GetApplicationList_Call) RunAndReturn(run func(ctx context.Context) ([]applicationConfigDAO, error)) *applicationStoreInterfaceMock_GetApplicationList_Call {
	_c.Call.Return(run)
	return _c
}

// GetOAuthConfigByAppID provides a mock function for the type applicationStoreInterfaceMock
func (_mock *applicationStoreInterfaceMock) GetOAuthConfigByAppID(ctx context.Context, entityID string) (*oauthConfigDAO, error) {
	ret := _mock.Called(ctx, entityID)

	if len(ret) == 0 {
		panic("no return value specified for GetOAuthConfigByAppID")
	}

	var r0 *oauthConfigDAO
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*oauthConfigDAO, error)); ok {
		return returnFunc(ctx, entityID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *oauthConfigDAO); ok {
		r0 = returnFunc(ctx, entityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*oauthConfigDAO)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, entityID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// applicationStoreInterfaceMock_GetOAuthConfigByAppID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOAuthConfigByAppID'
type applicationStoreInterfaceMock_GetOAuthConfigByAppID_Call struct {
	*mock.Call
}

// GetOAuthConfigByAppID is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID string
func (_e *applicationStoreInterfaceMock_Expecter) GetOAuthConfigByAppID(ctx interface{}, entityID interface{}) *applicationStoreInterfaceMock_GetOAuthConfigByAppID_Call {
	return &applicationStoreInterfaceMock_GetOAuthConfigByAppID_Call{Call: _e.mock.On("GetOAuthConfigByAppID", ctx, entityID)}
}

func (_c *applicationStoreInterfaceMock_GetOAuthConfigByAppID_Call) Run(run func(ctx context.Context, entityID string)) *applicationStoreInterfaceMock_GetOAuthConfigByAppID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *applicationStoreInterfaceMock_GetOAuthConfigByAppID_Call) Return(oauthConfigDAOMoqParam *oauthConfigDAO, err error) *applicationStoreInterfaceMock_GetOAuthConfigByAppID_Call {
	_c.Call.Return(oauthConfigDAOMoqParam, err)
	return _c
}

func (_c *applicationStoreInterfaceMock_GetOAuthConfigByAppID_Call) RunAndReturn(run func(ctx context.Context, entityID string) (*oauthConfigDAO, error)) *applicationStoreInterfaceMock_GetOAuthConfigByAppID_Call {
	_c.Call.Return(run)
	return _c
}

// GetTotalApplicationCount provides a mock function for the type applicationStoreInterfaceMock
func (_mock *applicationStoreInterfaceMock) GetTotalApplicationCount(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalApplicationCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// applicationStoreInterfaceMock_GetTotalApplicationCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTotalApplicationCount'
type applicationStoreInterfaceMock_GetTotalApplicationCount_Call struct {
	*mock.Call
}

// GetTotalApplicationCount is a helper method to define mock.On call
//   - ctx context.Context
func (_e *applicationStoreInterfaceMock_Expecter) GetTotalApplicationCount(ctx interface{}) *applicationStoreInterfaceMock_GetTotalApplicationCount_Call {
	return &applicationStoreInterfaceMock_GetTotalApplicationCount_Call{Call: _e.mock.On("GetTotalApplicationCount", ctx)}
}

func (_c *applicationStoreInterfaceMock_GetTotalApplicationCount_Call) Run(run func(ctx context.Context)) *applicationStoreInterfaceMock_GetTotalApplicationCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *applicationStoreInterfaceMock_GetTotalApplicationCount_Call) Return(n int, err error) *applicationStoreInterfaceMock_GetTotalApplicationCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *applicationStoreInterfaceMock_GetTotalApplicationCount_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *applicationStoreInterfaceMock_GetTotalApplicationCount_Call {
	_c.Call.Return(run)
	return _c
}

// IsApplicationDeclarative provides a mock function for the type applicationStoreInterfaceMock
func (_mock *applicationStoreInterfaceMock) IsApplicationDeclarative(ctx context.Context, id string) bool {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IsApplicationDeclarative")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// applicationStoreInterfaceMock_IsApplicationDeclarative_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsApplicationDeclarative'
type applicationStoreInterfaceMock_IsApplicationDeclarative_Call struct {
	*mock.Call
}

// IsApplicationDeclarative is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *applicationStoreInterfaceMock_Expecter) IsApplicationDeclarative(ctx interface{}, id interface{}) *applicationStoreInterfaceMock_IsApplicationDeclarative_Call {
	return &applicationStoreInterfaceMock_IsApplicationDeclarative_Call{Call: _e.mock.On("IsApplicationDeclarative", ctx, id)}
}

func (_c *applicationStoreInterfaceMock_IsApplicationDeclarative_Call) Run(run func(ctx context.Context, id string)) *applicationStoreInterfaceMock_IsApplicationDeclarative_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *applicationStoreInterfaceMock_IsApplicationDeclarative_Call) Return(b bool) *applicationStoreInterfaceMock_IsApplicationDeclarative_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *applicationStoreInterfaceMock_IsApplicationDeclarative_Call) RunAndReturn(run func(ctx context.Context, id string) bool) *applicationStoreInterfaceMock_IsApplicationDeclarative_Call {
	_c.Call.Return(run)
	return _c
}

// IsApplicationExists provides a mock function for the type applicationStoreInterfaceMock
func (_mock *applicationStoreInterfaceMock) IsApplicationExists(ctx context.Context, id string) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IsApplicationExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// applicationStoreInterfaceMock_IsApplicationExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsApplicationExists'
type applicationStoreInterfaceMock_IsApplicationExists_Call struct {
	*mock.Call
}

// IsApplicationExists is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *applicationStoreInterfaceMock_Expecter) IsApplicationExists(ctx interface{}, id interface{}) *applicationStoreInterfaceMock_IsApplicationExists_Call {
	return &applicationStoreInterfaceMock_IsApplicationExists_Call{Call: _e.mock.On("IsApplicationExists", ctx, id)}
}

func (_c *applicationStoreInterfaceMock_IsApplicationExists_Call) Run(run func(ctx context.Context, id string)) *applicationStoreInterfaceMock_IsApplicationExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *applicationStoreInterfaceMock_IsApplicationExists_Call) Return(b bool, err error) *applicationStoreInterfaceMock_IsApplicationExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *applicationStoreInterfaceMock_IsApplicationExists_Call) RunAndReturn(run func(ctx context.Context, id string) (bool, error)) *applicationStoreInterfaceMock_IsApplicationExists_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateApplication provides a mock function for the type applicationStoreInterfaceMock
func (_mock *applicationStoreInterfaceMock) UpdateApplication(ctx context.Context, app applicationConfigDAO) error {
	ret := _mock.Called(ctx, app)

	if len(ret) == 0 {
		panic("no return value specified for UpdateApplication")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, applicationConfigDAO) error); ok {
		r0 = returnFunc(ctx, app)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// applicationStoreInterfaceMock_UpdateApplication_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateApplication'
type applicationStoreInterfaceMock_UpdateApplication_Call struct {
	*mock.Call
}

// UpdateApplication is a helper method to define mock.On call
//   - ctx context.Context
//   - app applicationConfigDAO
func (_e *applicationStoreInterfaceMock_Expecter) UpdateApplication(ctx interface{}, app interface{}) *applicationStoreInterfaceMock_UpdateApplication_Call {
	return &applicationStoreInterfaceMock_UpdateApplication_Call{Call: _e.mock.On("UpdateApplication", ctx, app)}
}

func (_c *applicationStoreInterfaceMock_UpdateApplication_Call) Run(run func(ctx context.Context, app applicationConfigDAO)) *applicationStoreInterfaceMock_UpdateApplication_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 applicationConfigDAO
		if args[1] != nil {
			arg1 = args[1].(applicationConfigDAO)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *applicationStoreInterfaceMock_UpdateApplication_Call) Return(err error) *applicationStoreInterfaceMock_UpdateApplication_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *applicationStoreInterfaceMock_UpdateApplication_Call) RunAndReturn(run func(ctx context.Context, app applicationConfigDAO) error) *applicationStoreInterfaceMock_UpdateApplication_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOAuthConfig provides a mock function for the type applicationStoreInterfaceMock
func (_mock *applicationStoreInterfaceMock) UpdateOAuthConfig(ctx context.Context, entityID string, oauthConfigJSON json.RawMessage) error {
	ret := _mock.Called(ctx, entityID, oauthConfigJSON)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOAuthConfig")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, json.RawMessage) error); ok {
		r0 = returnFunc(ctx, entityID, oauthConfigJSON)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// applicationStoreInterfaceMock_UpdateOAuthConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOAuthConfig'
type applicationStoreInterfaceMock_UpdateOAuthConfig_Call struct {
	*mock.Call
}

// UpdateOAuthConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID string
//   - oauthConfigJSON json.RawMessage
func (_e *applicationStoreInterfaceMock_Expecter) UpdateOAuthConfig(ctx interface{}, entityID interface{}, oauthConfigJSON interface{}) *applicationStoreInterfaceMock_UpdateOAuthConfig_Call {
	return &applicationStoreInterfaceMock_UpdateOAuthConfig_Call{Call: _e.mock.On("UpdateOAuthConfig", ctx, entityID, oauthConfigJSON)}
}

func (_c *applicationStoreInterfaceMock_UpdateOAuthConfig_Call) Run(run func(ctx context.Context, entityID string, oauthConfigJSON json.RawMessage)) *applicationStoreInterfaceMock_UpdateOAuthConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 json.RawMessage
		if args[2] != nil {
			arg2 = args[2].(json.RawMessage)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *applicationStoreInterfaceMock_UpdateOAuthConfig_Call) Return(err error) *applicationStoreInterfaceMock_UpdateOAuthConfig_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *applicationStoreInterfaceMock_UpdateOAuthConfig_Call) RunAndReturn(run func(ctx context.Context, entityID string, oauthConfigJSON json.RawMessage) error) *applicationStoreInterfaceMock_UpdateOAuthConfig_Call {
	_c.Call.Return(run)
	return _c
}
