// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package userschema

import (
	"context"
	"encoding/json"

	"github.com/asgardeo/thunder/internal/system/error/serviceerror"
	mock "github.com/stretchr/testify/mock"
)

// NewUserSchemaServiceInterfaceMock creates a new instance of UserSchemaServiceInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserSchemaServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserSchemaServiceInterfaceMock {
	mock := &UserSchemaServiceInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserSchemaServiceInterfaceMock is an autogenerated mock type for the UserSchemaServiceInterface type
type UserSchemaServiceInterfaceMock struct {
	mock.Mock
}

type UserSchemaServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UserSchemaServiceInterfaceMock) EXPECT() *UserSchemaServiceInterfaceMock_Expecter {
	return &UserSchemaServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// CreateUserSchema provides a mock function for the type UserSchemaServiceInterfaceMock
func (_mock *UserSchemaServiceInterfaceMock) CreateUserSchema(ctx context.Context, request CreateUserSchemaRequestWithID) (*UserSchema, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserSchema")
	}

	var r0 *UserSchema
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateUserSchemaRequestWithID) (*UserSchema, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, CreateUserSchemaRequestWithID) *UserSchema); ok {
		r0 = returnFunc(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*UserSchema)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, CreateUserSchemaRequestWithID) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// UserSchemaServiceInterfaceMock_CreateUserSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserSchema'
type UserSchemaServiceInterfaceMock_CreateUserSchema_Call struct {
	*mock.Call
}

// CreateUserSchema is a helper method to define mock.On call
//   - ctx context.Context
//   - request CreateUserSchemaRequestWithID
func (_e *UserSchemaServiceInterfaceMock_Expecter) CreateUserSchema(ctx interface{}, request interface{}) *UserSchemaServiceInterfaceMock_CreateUserSchema_Call {
	return &UserSchemaServiceInterfaceMock_CreateUserSchema_Call{Call: _e.mock.On("CreateUserSchema", ctx, request)}
}

func (_c *UserSchemaServiceInterfaceMock_CreateUserSchema_Call) Run(run func(ctx context.Context, request CreateUserSchemaRequestWithID)) *UserSchemaServiceInterfaceMock_CreateUserSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 CreateUserSchemaRequestWithID
		if args[1] != nil {
			arg1 = args[1].(CreateUserSchemaRequestWithID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_CreateUserSchema_Call) Return(userSchema *UserSchema, serviceError *serviceerror.ServiceError) *UserSchemaServiceInterfaceMock_CreateUserSchema_Call {
	_c.Call.Return(userSchema, serviceError)
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_CreateUserSchema_Call) RunAndReturn(run func(ctx context.Context, request CreateUserSchemaRequestWithID) (*UserSchema, *serviceerror.ServiceError)) *UserSchemaServiceInterfaceMock_CreateUserSchema_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserSchema provides a mock function for the type UserSchemaServiceInterfaceMock
func (_mock *UserSchemaServiceInterfaceMock) DeleteUserSchema(ctx context.Context, schemaID string) *serviceerror.ServiceError {
	ret := _mock.Called(ctx, schemaID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserSchema")
	}

	var r0 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *serviceerror.ServiceError); ok {
		r0 = returnFunc(ctx, schemaID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*serviceerror.ServiceError)
		}
	}
	return r0
}

// UserSchemaServiceInterfaceMock_DeleteUserSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserSchema'
type UserSchemaServiceInterfaceMock_DeleteUserSchema_Call struct {
	*mock.Call
}

// DeleteUserSchema is a helper method to define mock.On call
//   - ctx context.Context
//   - schemaID string
func (_e *UserSchemaServiceInterfaceMock_Expecter) DeleteUserSchema(ctx interface{}, schemaID interface{}) *UserSchemaServiceInterfaceMock_DeleteUserSchema_Call {
	return &UserSchemaServiceInterfaceMock_DeleteUserSchema_Call{Call: _e.mock.On("DeleteUserSchema", ctx, schemaID)}
}

func (_c *UserSchemaServiceInterfaceMock_DeleteUserSchema_Call) Run(run func(ctx context.Context, schemaID string)) *UserSchemaServiceInterfaceMock_DeleteUserSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_DeleteUserSchema_Call) Return(serviceError *serviceerror.ServiceError) *UserSchemaServiceInterfaceMock_DeleteUserSchema_Call {
	_c.Call.Return(serviceError)
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_DeleteUserSchema_Call) RunAndReturn(run func(ctx context.Context, schemaID string) *serviceerror.ServiceError) *UserSchemaServiceInterfaceMock_DeleteUserSchema_Call {
	_c.Call.Return(run)
	return _c
}

// GetCredentialAttributes provides a mock function for the type UserSchemaServiceInterfaceMock
func (_mock *UserSchemaServiceInterfaceMock) GetCredentialAttributes(ctx context.Context, userType string) ([]string, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, userType)

	if len(ret) == 0 {
		panic("no return value specified for GetCredentialAttributes")
	}

	var r0 []string
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, userType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, userType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, userType)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// UserSchemaServiceInterfaceMock_GetCredentialAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCredentialAttributes'
type UserSchemaServiceInterfaceMock_GetCredentialAttributes_Call struct {
	*mock.Call
}

// GetCredentialAttributes is a helper method to define mock.On call
//   - ctx context.Context
//   - userType string
func (_e *UserSchemaServiceInterfaceMock_Expecter) GetCredentialAttributes(ctx interface{}, userType interface{}) *UserSchemaServiceInterfaceMock_GetCredentialAttributes_Call {
	return &UserSchemaServiceInterfaceMock_GetCredentialAttributes_Call{Call: _e.mock.On("GetCredentialAttributes", ctx, userType)}
}

func (_c *UserSchemaServiceInterfaceMock_GetCredentialAttributes_Call) Run(run func(ctx context.Context, userType string)) *UserSchemaServiceInterfaceMock_GetCredentialAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_GetCredentialAttributes_Call) Return(strings []string, serviceError *serviceerror.ServiceError) *UserSchemaServiceInterfaceMock_GetCredentialAttributes_Call {
	_c.Call.Return(strings, serviceError)
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_GetCredentialAttributes_Call) RunAndReturn(run func(ctx context.Context, userType string) ([]string, *serviceerror.ServiceError)) *UserSchemaServiceInterfaceMock_GetCredentialAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// GetDisplayAttributesByNames provides a mock function for the type UserSchemaServiceInterfaceMock
func (_mock *UserSchemaServiceInterfaceMock) GetDisplayAttributesByNames(ctx context.Context, names []string) (map[string]string, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, names)

	if len(ret) == 0 {
		panic("no return value specified for GetDisplayAttributesByNames")
	}

	var r0 map[string]string
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) (map[string]string, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, names)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string) map[string]string); ok {
		r0 = returnFunc(ctx, names)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, names)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// UserSchemaServiceInterfaceMock_GetDisplayAttributesByNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDisplayAttributesByNames'
type UserSchemaServiceInterfaceMock_GetDisplayAttributesByNames_Call struct {
	*mock.Call
}

// GetDisplayAttributesByNames is a helper method to define mock.On call
//   - ctx context.Context
//   - names []string
func (_e *UserSchemaServiceInterfaceMock_Expecter) GetDisplayAttributesByNames(ctx interface{}, names interface{}) *UserSchemaServiceInterfaceMock_GetDisplayAttributesByNames_Call {
	return &UserSchemaServiceInterfaceMock_GetDisplayAttributesByNames_Call{Call: _e.mock.On("GetDisplayAttributesByNames", ctx, names)}
}

func (_c *UserSchemaServiceInterfaceMock_GetDisplayAttributesByNames_Call) Run(run func(ctx context.Context, names []string)) *UserSchemaServiceInterfaceMock_GetDisplayAttributesByNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_GetDisplayAttributesByNames_Call) Return(stringToString map[string]string, serviceError *serviceerror.ServiceError) *UserSchemaServiceInterfaceMock_GetDisplayAttributesByNames_Call {
	_c.Call.Return(stringToString, serviceError)
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_GetDisplayAttributesByNames_Call) RunAndReturn(run func(ctx context.Context, names []string) (map[string]string, *serviceerror.ServiceError)) *UserSchemaServiceInterfaceMock_GetDisplayAttributesByNames_Call {
	_c.Call.Return(run)
	return _c
}

// GetUniqueAttributes provides a mock function for the type UserSchemaServiceInterfaceMock
func (_mock *UserSchemaServiceInterfaceMock) GetUniqueAttributes(ctx context.Context, userType string) ([]string, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, userType)

	if len(ret) == 0 {
		panic("no return value specified for GetUniqueAttributes")
	}

	var r0 []string
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, userType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, userType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, userType)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// UserSchemaServiceInterfaceMock_GetUniqueAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUniqueAttributes'
type UserSchemaServiceInterfaceMock_GetUniqueAttributes_Call struct {
	*mock.Call
}

// GetUniqueAttributes is a helper method to define mock.On call
//   - ctx context.Context
//   - userType string
func (_e *UserSchemaServiceInterfaceMock_Expecter) GetUniqueAttributes(ctx interface{}, userType interface{}) *UserSchemaServiceInterfaceMock_GetUniqueAttributes_Call {
	return &UserSchemaServiceInterfaceMock_GetUniqueAttributes_Call{Call: _e.mock.On("GetUniqueAttributes", ctx, userType)}
}

func (_c *UserSchemaServiceInterfaceMock_GetUniqueAttributes_Call) Run(run func(ctx context.Context, userType string)) *UserSchemaServiceInterfaceMock_GetUniqueAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_GetUniqueAttributes_Call) Return(strings []string, serviceError *serviceerror.ServiceError) *UserSchemaServiceInterfaceMock_GetUniqueAttributes_Call {
	_c.Call.Return(strings, serviceError)
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_GetUniqueAttributes_Call) RunAndReturn(run func(ctx context.Context, userType string) ([]string, *serviceerror.ServiceError)) *UserSchemaServiceInterfaceMock_GetUniqueAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserSchema provides a mock function for the type UserSchemaServiceInterfaceMock
func (_mock *UserSchemaServiceInterfaceMock) GetUserSchema(ctx context.Context, schemaID string, includeDisplay bool) (*UserSchema, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, schemaID, includeDisplay)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSchema")
	}

	var r0 *UserSchema
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) (*UserSchema, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, schemaID, includeDisplay)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) *UserSchema); ok {
		r0 = returnFunc(ctx, schemaID, includeDisplay)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*UserSchema)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, schemaID, includeDisplay)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// UserSchemaServiceInterfaceMock_GetUserSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserSchema'
type UserSchemaServiceInterfaceMock_GetUserSchema_Call struct {
	*mock.Call
}

// GetUserSchema is a helper method to define mock.On call
//   - ctx context.Context
//   - schemaID string
//   - includeDisplay bool
func (_e *UserSchemaServiceInterfaceMock_Expecter) GetUserSchema(ctx interface{}, schemaID interface{}, includeDisplay interface{}) *UserSchemaServiceInterfaceMock_GetUserSchema_Call {
	return &UserSchemaServiceInterfaceMock_GetUserSchema_Call{Call: _e.mock.On("GetUserSchema", ctx, schemaID, includeDisplay)}
}

func (_c *UserSchemaServiceInterfaceMock_GetUserSchema_Call) Run(run func(ctx context.Context, schemaID string, includeDisplay bool)) *UserSchemaServiceInterfaceMock_GetUserSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_GetUserSchema_Call) Return(userSchema *UserSchema, serviceError *serviceerror.ServiceError) *UserSchemaServiceInterfaceMock_GetUserSchema_Call {
	_c.Call.Return(userSchema, serviceError)
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_GetUserSchema_Call) RunAndReturn(run func(ctx context.Context, schemaID string, includeDisplay bool) (*UserSchema, *serviceerror.ServiceError)) *UserSchemaServiceInterfaceMock_GetUserSchema_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserSchemaByName provides a mock function for the type UserSchemaServiceInterfaceMock
func (_mock *UserSchemaServiceInterfaceMock) GetUserSchemaByName(ctx context.Context, schemaName string) (*UserSchema, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, schemaName)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSchemaByName")
	}

	var r0 *UserSchema
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*UserSchema, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, schemaName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *UserSchema); ok {
		r0 = returnFunc(ctx, schemaName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*UserSchema)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, schemaName)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// UserSchemaServiceInterfaceMock_GetUserSchemaByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserSchemaByName'
type UserSchemaServiceInterfaceMock_GetUserSchemaByName_Call struct {
	*mock.Call
}

// GetUserSchemaByName is a helper method to define mock.On call
//   - ctx context.Context
//   - schemaName string
func (_e *UserSchemaServiceInterfaceMock_Expecter) GetUserSchemaByName(ctx interface{}, schemaName interface{}) *UserSchemaServiceInterfaceMock_GetUserSchemaByName_Call {
	return &UserSchemaServiceInterfaceMock_GetUserSchemaByName_Call{Call: _e.mock.On("GetUserSchemaByName", ctx, schemaName)}
}

func (_c *UserSchemaServiceInterfaceMock_GetUserSchemaByName_Call) Run(run func(ctx context.Context, schemaName string)) *UserSchemaServiceInterfaceMock_GetUserSchemaByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_GetUserSchemaByName_Call) Return(userSchema *UserSchema, serviceError *serviceerror.ServiceError) *UserSchemaServiceInterfaceMock_GetUserSchemaByName_Call {
	_c.Call.Return(userSchema, serviceError)
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_GetUserSchemaByName_Call) RunAndReturn(run func(ctx context.Context, schemaName string) (*UserSchema, *serviceerror.ServiceError)) *UserSchemaServiceInterfaceMock_GetUserSchemaByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserSchemaList provides a mock function for the type UserSchemaServiceInterfaceMock
func (_mock *UserSchemaServiceInterfaceMock) GetUserSchemaList(ctx context.Context, limit int, offset int, includeDisplay bool) (*UserSchemaListResponse, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, limit, offset, includeDisplay)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSchemaList")
	}

	var r0 *UserSchemaListResponse
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, bool) (*UserSchemaListResponse, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, limit, offset, includeDisplay)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, bool) *UserSchemaListResponse); ok {
		r0 = returnFunc(ctx, limit, offset, includeDisplay)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*UserSchemaListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, bool) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, limit, offset, includeDisplay)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// UserSchemaServiceInterfaceMock_GetUserSchemaList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserSchemaList'
type UserSchemaServiceInterfaceMock_GetUserSchemaList_Call struct {
	*mock.Call
}

// GetUserSchemaList is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
//   - includeDisplay bool
func (_e *UserSchemaServiceInterfaceMock_Expecter) GetUserSchemaList(ctx interface{}, limit interface{}, offset interface{}, includeDisplay interface{}) *UserSchemaServiceInterfaceMock_GetUserSchemaList_Call {
	return &UserSchemaServiceInterfaceMock_GetUserSchemaList_Call{Call: _e.mock.On("GetUserSchemaList", ctx, limit, offset, includeDisplay)}
}

func (_c *UserSchemaServiceInterfaceMock_GetUserSchemaList_Call) Run(run func(ctx context.Context, limit int, offset int, includeDisplay bool)) *UserSchemaServiceInterfaceMock_GetUserSchemaList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_GetUserSchemaList_Call) Return(userSchemaListResponse *UserSchemaListResponse, serviceError *serviceerror.ServiceError) *UserSchemaServiceInterfaceMock_GetUserSchemaList_Call {
	_c.Call.Return(userSchemaListResponse, serviceError)
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_GetUserSchemaList_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int, includeDisplay bool) (*UserSchemaListResponse, *serviceerror.ServiceError)) *UserSchemaServiceInterfaceMock_GetUserSchemaList_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserSchema provides a mock function for the type UserSchemaServiceInterfaceMock
func (_mock *UserSchemaServiceInterfaceMock) UpdateUserSchema(ctx context.Context, schemaID string, request UpdateUserSchemaRequest) (*UserSchema, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, schemaID, request)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserSchema")
	}

	var r0 *UserSchema
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, UpdateUserSchemaRequest) (*UserSchema, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, schemaID, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, UpdateUserSchemaRequest) *UserSchema); ok {
		r0 = returnFunc(ctx, schemaID, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*UserSchema)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, UpdateUserSchemaRequest) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, schemaID, request)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// UserSchemaServiceInterfaceMock_UpdateUserSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserSchema'
type UserSchemaServiceInterfaceMock_UpdateUserSchema_Call struct {
	*mock.Call
}

// UpdateUserSchema is a helper method to define mock.On call
//   - ctx context.Context
//   - schemaID string
//   - request UpdateUserSchemaRequest
func (_e *UserSchemaServiceInterfaceMock_Expecter) UpdateUserSchema(ctx interface{}, schemaID interface{}, request interface{}) *UserSchemaServiceInterfaceMock_UpdateUserSchema_Call {
	return &UserSchemaServiceInterfaceMock_UpdateUserSchema_Call{Call: _e.mock.On("UpdateUserSchema", ctx, schemaID, request)}
}

func (_c *UserSchemaServiceInterfaceMock_UpdateUserSchema_Call) Run(run func(ctx context.Context, schemaID string, request UpdateUserSchemaRequest)) *UserSchemaServiceInterfaceMock_UpdateUserSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 UpdateUserSchemaRequest
		if args[2] != nil {
			arg2 = args[2].(UpdateUserSchemaRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_UpdateUserSchema_Call) Return(userSchema *UserSchema, serviceError *serviceerror.ServiceError) *UserSchemaServiceInterfaceMock_UpdateUserSchema_Call {
	_c.Call.Return(userSchema, serviceError)
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_UpdateUserSchema_Call) RunAndReturn(run func(ctx context.Context, schemaID string, request UpdateUserSchemaRequest) (*UserSchema, *serviceerror.ServiceError)) *UserSchemaServiceInterfaceMock_UpdateUserSchema_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateUser provides a mock function for the type UserSchemaServiceInterfaceMock
func (_mock *UserSchemaServiceInterfaceMock) ValidateUser(ctx context.Context, userType string, userAttributes json.RawMessage, skipCredentialRequired bool) (bool, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, userType, userAttributes, skipCredentialRequired)

	if len(ret) == 0 {
		panic("no return value specified for ValidateUser")
	}

	var r0 bool
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, json.RawMessage, bool) (bool, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, userType, userAttributes, skipCredentialRequired)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, json.RawMessage, bool) bool); ok {
		r0 = returnFunc(ctx, userType, userAttributes, skipCredentialRequired)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, json.RawMessage, bool) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, userType, userAttributes, skipCredentialRequired)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// UserSchemaServiceInterfaceMock_ValidateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateUser'
type UserSchemaServiceInterfaceMock_ValidateUser_Call struct {
	*mock.Call
}

// ValidateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userType string
//   - userAttributes json.RawMessage
//   - skipCredentialRequired bool
func (_e *UserSchemaServiceInterfaceMock_Expecter) ValidateUser(ctx interface{}, userType interface{}, userAttributes interface{}, skipCredentialRequired interface{}) *UserSchemaServiceInterfaceMock_ValidateUser_Call {
	return &UserSchemaServiceInterfaceMock_ValidateUser_Call{Call: _e.mock.On("ValidateUser", ctx, userType, userAttributes, skipCredentialRequired)}
}

func (_c *UserSchemaServiceInterfaceMock_ValidateUser_Call) Run(run func(ctx context.Context, userType string, userAttributes json.RawMessage, skipCredentialRequired bool)) *UserSchemaServiceInterfaceMock_ValidateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 json.RawMessage
		if args[2] != nil {
			arg2 = args[2].(json.RawMessage)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_ValidateUser_Call) Return(b bool, serviceError *serviceerror.ServiceError) *UserSchemaServiceInterfaceMock_ValidateUser_Call {
	_c.Call.Return(b, serviceError)
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_ValidateUser_Call) RunAndReturn(run func(ctx context.Context, userType string, userAttributes json.RawMessage, skipCredentialRequired bool) (bool, *serviceerror.ServiceError)) *UserSchemaServiceInterfaceMock_ValidateUser_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateUserUniqueness provides a mock function for the type UserSchemaServiceInterfaceMock
func (_mock *UserSchemaServiceInterfaceMock) ValidateUserUniqueness(ctx context.Context, userType string, userAttributes json.RawMessage, exists func(map[string]interface{}) (bool, error)) (bool, *serviceerror.ServiceError) {
	ret := _mock.Called(ctx, userType, userAttributes, exists)

	if len(ret) == 0 {
		panic("no return value specified for ValidateUserUniqueness")
	}

	var r0 bool
	var r1 *serviceerror.ServiceError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, json.RawMessage, func(map[string]interface{}) (bool, error)) (bool, *serviceerror.ServiceError)); ok {
		return returnFunc(ctx, userType, userAttributes, exists)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, json.RawMessage, func(map[string]interface{}) (bool, error)) bool); ok {
		r0 = returnFunc(ctx, userType, userAttributes, exists)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, json.RawMessage, func(map[string]interface{}) (bool, error)) *serviceerror.ServiceError); ok {
		r1 = returnFunc(ctx, userType, userAttributes, exists)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*serviceerror.ServiceError)
		}
	}
	return r0, r1
}

// UserSchemaServiceInterfaceMock_ValidateUserUniqueness_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateUserUniqueness'
type UserSchemaServiceInterfaceMock_ValidateUserUniqueness_Call struct {
	*mock.Call
}

// ValidateUserUniqueness is a helper method to define mock.On call
//   - ctx context.Context
//   - userType string
//   - userAttributes json.RawMessage
//   - exists func(map[string]interface{}) (bool, error)
func (_e *UserSchemaServiceInterfaceMock_Expecter) ValidateUserUniqueness(ctx interface{}, userType interface{}, userAttributes interface{}, exists interface{}) *UserSchemaServiceInterfaceMock_ValidateUserUniqueness_Call {
	return &UserSchemaServiceInterfaceMock_ValidateUserUniqueness_Call{Call: _e.mock.On("ValidateUserUniqueness", ctx, userType, userAttributes, exists)}
}

func (_c *UserSchemaServiceInterfaceMock_ValidateUserUniqueness_Call) Run(run func(ctx context.Context, userType string, userAttributes json.RawMessage, exists func(map[string]interface{}) (bool, error))) *UserSchemaServiceInterfaceMock_ValidateUserUniqueness_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 json.RawMessage
		if args[2] != nil {
			arg2 = args[2].(json.RawMessage)
		}
		var arg3 func(map[string]interface{}) (bool, error)
		if args[3] != nil {
			arg3 = args[3].(func(map[string]interface{}) (bool, error))
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_ValidateUserUniqueness_Call) Return(b bool, serviceError *serviceerror.ServiceError) *UserSchemaServiceInterfaceMock_ValidateUserUniqueness_Call {
	_c.Call.Return(b, serviceError)
	return _c
}

func (_c *UserSchemaServiceInterfaceMock_ValidateUserUniqueness_Call) RunAndReturn(run func(ctx context.Context, userType string, userAttributes json.RawMessage, exists func(map[string]interface{}) (bool, error)) (bool, *serviceerror.ServiceError)) *UserSchemaServiceInterfaceMock_ValidateUserUniqueness_Call {
	_c.Call.Return(run)
	return _c
}
